mod_id=streetparts
mod_name=Streetparts
mod_version=1.2
mod_group_id=com.shredemption.streetparts
mod_license=MIT
mod_authors=Shredemption
mod_description=Streetparts mod for Minecraft 1.21.1

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.62
loader_version_range=[1,)
parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10
