modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="streetparts"
version="1.2"
displayName="Streetparts"
description='Streetparts mod for Minecraft 1.21.1'
authors=["Shredemption"]